From 03965bb042335a66d006412890bf685e8be5163f Mon Sep 17 00:00:00 2001 Subject: [PATCH 8/9] SDL_gfx patch: add missing SDL_gfxFastDraw
This is required to avoid undefined reference to getDrawRoutine